### ISSUE TITLE
Cannot link mgba-qt

### ISSUE THREAD

**Issue by duganchen** [mgba-emu/mgba#154]
Trying to build mGBA with Qt support fails for me with the following error:

```
Linking CXX executable mgba-qt
/tmp/ccPQxOIt.ltrans20.ltrans.o: In function `QGBA::AudioProcessorSDL::AudioProcessorSDL(QObject*)':
ccPQxOIt.ltrans20.o:(.text+0x84c): undefined reference to `vtable for QGBA::AudioProcessorSDL'
/tmp/ccPQxOIt.ltrans25.ltrans.o: In function `QGBA::AudioProcessorSDL::~AudioProcessorSDL()':
ccPQxOIt.ltrans25.o:(.text+0xf73): undefined reference to `vtable for QGBA::AudioProcessorSDL'
/tmp/ccPQxOIt.ltrans25.ltrans.o: In function `QGBA::AudioProcessorSDL::start()':
ccPQxOIt.ltrans25.o:(.text+0x1aab): undefined reference to `QGBA::AudioProcessorSDL::staticMetaObject'
collect2: error: ld returned 1 exit status
make[2]: *** [qt/mgba-qt] Error 1
make[1]: *** [qt/CMakeFiles/mgba-qt.dir/all] Error 2
make: *** [all] Error 2
```

I'm using Slackware64 14.1, with Qt 5.5.0, and gcc 4.8.2.

**Comment by endrift** [comment]
Does cmake say that SDL is enabled? Does it try to compile AudioProcessorSDL.cpp?

**Comment by duganchen** [comment]
Yes to both.

**Comment by endrift** [comment]
Is this from a fresh working tree? This looks like it didn't rebuild AudioProcessorSDL properly at one point. SDL1.2 or 2? It shouldn't really make a difference though… Do you have a modern CMake?

**Comment by duganchen** [comment]
It's from a fresh working tree, yes. SDL2. CMake is at 2.8.12.

**Comment by endrift** [comment]
Strange. It kind of looks like it's not running moc properly, but that would be CMake's fault. If at all possible, can you update CMake to 3.x to see if it fixes anything?

**Comment by duganchen** [comment]
Builds fine with CMake 3.3.2.

**Comment by endrift** [comment]
Guess I might want to bump the CMake version dependency, or figure out what's going wrong on older CMakes. Sigh.
