### PR TITLE
Qt: Fix build with Qt 5.10

### PR DESCRIPTION
**Pull request by ilovezfs**
Fixes "MemoryModel.cpp:102:15: error: no viable overloaded '='"

### CODE REVIEW

**Comment by rootfather** [comment]
I can confirm that building on Qt 5.10 is currently broken and that this patch fixes this.

**Comment by ilovezfs** [comment]
The failure on Travis's `osx` image is the same as the one I reported here: https://github.com/mgba-emu/mgba/issues/944
