### ISSUE TITLE
Build failure with SDL 1.2

### ISSUE THREAD

**Issue by xTibor** [mgba-emu/mgba#1128]
```
/home/user/git/mgba/src/platform/sdl/sdl-events.c: In function ‘_mSDLHandleKeypress’:
/home/user/git/mgba/src/platform/sdl/sdl-events.c:413:25: error: ‘const struct SDL_KeyboardEvent’ has no member named ‘repeat’
  if (key != -1 && !event->repeat) {
                         ^
sdl/CMakeFiles/mgba-sdl.dir/build.make:62: recipe for target 'sdl/CMakeFiles/mgba-sdl.dir/sdl-events.c.o' failed
```

Introduced by https://github.com/mgba-emu/mgba/commit/932b8117a4d83632534536a8b87b8dafcafefbe0. In SDL 1.2 the `SDL_KeyboardEvent` struct [doesn't seem to have](https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlkeyboardevent.html) that `repeat` field.

**Comment by endrift** [comment]
Should be fixed now.
